site_name: The Egon Framework
theme:
  name: material
  custom_dir: docs/_overrides
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - search.suggest
  plugins:
    - offline
    - search
    - mkdocstrings
markdown_extensions:
  - neoteroi.cards
extra_css:
  - _css/neoteroi/neoteroi-mkdocs.css
  - _css/hide_sidebar.css
extra:
  analytics:
    provider: google
    property: !ENV ANALYTICS_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! 
            If you have an issue or question not addressed by our documentation, we encourage you to 
            <a href="..." target="_blank" rel="noopener">submit a GitHub issue</a>.
  consent:
    title: Cookie Consent Policy
    description: >-
      This site uses cookies to recognize your repeated visits and preferences.
      This information is used to improve our documentation and ensure users find what they're searching for. 
      Please consider helping us make better documentation by enabling cookies.
    actions:
      - manage
      - accept
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  generator: false
copyright: Copyright &copy; – <a href="#__consent">Change cookie settings</a>
