site_name: The Egon Framework
theme:
  name: material
  custom_dir: docs/_overrides
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - search.suggest
plugins:
  - offline
  - search
  - mkdocstrings
  - monorepo
  - swagger-ui-tag:
      extra_css: [_assets/css/swagger.css]
markdown_extensions:
  - neoteroi.cards
  - md_in_html
extra_css:
  - _assets/css/neoteroi/neoteroi-mkdocs.css
  - _assets/css/hide_sidebar.css
extra:
  analytics:
    provider: google
    property: !ENV ANALYTICS_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! 
            If you have an issue or question not addressed by our documentation, we encourage you to 
            <a href="..." target="_blank" rel="noopener">submit a GitHub issue</a>.
  consent:
    title: Cookie Consent Policy
    description: >-
      This site uses cookies to recognize your repeated visits and preferences.
      This information is used to improve our documentation and ensure users find what they're searching for. 
      Please consider helping us make better documentation by enabling cookies.
    actions:
      - manage
      - accept
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  generator: false
nav:
  - index.md
  - Getting Started:
      - getting_started/install_setup.md
  - Technical References:
    - technical_references/index.md
    - Egon: '!include docs/technical_references/egon/mkdocs.yml'
    - Egon Worker: '!include docs/technical_references/egon-worker/mkdocs.yml'
    - Egon Dashboard: '!include docs/technical_references/dashboard/mkdocs.yml'
    - Status API Server: '!include docs/technical_references/status-api-server/mkdocs.yml'
    - Status API Contract: '!include docs/technical_references/status-api-schema/mkdocs.yml'
copyright: Copyright &copy; The Egon Framework – <a href="#__consent">Change cookie settings</a>
