name: Build Documentation

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project source
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build documentation
        uses: ./.github/actions/build
