name: Build Documentation

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Checkout project source
        uses: actions/checkout@v3

      - name: Install python Dependencies
        run: pip install mkdocs-material

      - name: Build Docs
        run: mkdocs gh-deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site
